services:
  mongo:
    image: mongo:7.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
    - MONGO_INITDB_DATABASE=mundotechdb

volumes:  
  mongo_data:
